// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import (
	"time"
)

type User struct {
	UserID       string    `json:"user_id"`
	UserName     string    `json:"user_name"`
	Password     string    `json:"password"`
	Email        string    `json:"email"`
	UserType     string    `json:"user_type"`
	Token        string    `json:"token"`
	RefreshToken string    `json:"refresh_token"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
