// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import (
	"context"
)

type Querier interface {
	CheckUserByEmail(ctx context.Context, email string) (bool, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetAllUsers(ctx context.Context) ([]User, error)
	GetUser(ctx context.Context, userID string) (User, error)
}

var _ Querier = (*Queries)(nil)
